### ISSUE TITLE
Not showing up in Extension Pack query

### ISSUE THREAD

**Issue by waderyan** [felixfbecker/vscode-php-pack#2]
Hey @felixfbecker - wondering why this won't show Extension Packs under the category? Perhaps it wasn't published after you added that category. 

I want to feature it on the VS Code blog if you want to republish soon. 

(Look at Categories below... I expect to see Extension Packs)

![image](https://cloud.githubusercontent.com/assets/2449568/23567313/8e3270cc-000a-11e7-8061-49fa6a4e7f15.png)

Maybe its a bug on our side?

**Comment by felixfbecker** [comment]
Thanks for the heads-up, published!
Awesome you want to feature this, if there is anything I can help with let me know!
