### ISSUE TITLE
PHP Remote Debugger

### ISSUE THREAD

**Issue by aftabnaveed** [felixfbecker/vscode-php-pack#4]
I opened an issue on main VSCode which they said to be something which can be implemented through the PHP extension https://github.com/Microsoft/vscode/issues/43636#issuecomment-365524625 

I am not sure if this is something you or community would be interested in having it. I also see something similar for python https://github.com/Microsoft/vscode-python/issues/79

**Comment by felixfbecker** [comment]
You are free to run PHP on a remote host and connecting the debugger to it, that already works

**Comment by aftabnaveed** [comment]
That is an xDebug feature which is different than executing code such as composer, phpcs on remote server from the IDE :-)

**Comment by RoestVrijStaal** [comment]
@felixfbecker Would you please post all your PHP, VS Code, XDebug etc configs so the rest of the world could achieve the same results?

**Comment by felixfbecker** [comment]
@RoestVrijStaal I don't use this myself. All the things I know to work are outlined in the README

**Comment by RoestVrijStaal** [comment]
In other words, this project is pretty much unmaintained nowadays?
